### ISSUE TITLE
Display confirmation page ("are you sure?") after voting

### ISSUE THREAD

**Issue by gm2k12** [cidermole/civicracy#24]
Show an "Undo _this_ " button, for a few seconds, after performing an action.

Should at least be implemented for voting.

Another approach would be to show an "are you really sure you want to do this/that" before performing actions.

**Comment by cidermole** [comment]
I don't really agree: the interface is simple enough.

What I could imagine is an extra page after pressing the vote button, which again shows you the candidate you're voting for, his/her slogan and your entered reason.

**Comment by gm2k12** [comment]
Okay, agree too(..where can I see the current 'interface' actually..? (administration/voting) )

> What I could imagine is an extra page after pressing the vote button, which again shows you the candidate you're voting for, his/her slogan and your entered reason.

and I would put an "If you vote, you cannot change that vote for the next _number_ days" on that extra page too. Agree?

**Comment by cidermole** [comment]
ACK
